on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 1'  # every Monday

name: Run Tox tests

jobs:
  tox_test:
    name: Tox test
    steps:
    - uses: actions/checkout@v2
    - name: Run Tox tests
      id: test
      uses: fedora-python/tox-github-action@master
      with:
        tox_env: ${{ matrix.tox_env }}
    strategy:
      matrix:
        tox_env:
        # This information is repeated in tox.ini
        # (see https://github.com/fedora-python/tox-github-action/issues/8)
        # Generate it by: tox -l | sed "s/^/- /"
        - py36-toxrelease
        - py36-toxmaster
        - py36-toxtox315
        - py37-toxrelease
        - py37-toxmaster
        - py37-toxtox315
        - py38-toxrelease
        - py38-toxmaster
        - py38-toxtox315
        - py39-toxrelease
        - py39-toxmaster
        - py39-toxtox315
        - py310-toxrelease
        - py310-toxmaster
        - py310-toxtox315

    # Use GitHub's Linux Docker host
    runs-on: ubuntu-latest
