on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 1'  # every Monday

name: Run tox tests

jobs:
  tox_test:
    name: tox test
    steps:
    - uses: actions/checkout@v4
    - name: Run tox tests
      id: test
      uses: fedora-python/tox-github-action@main
      with:
        tox_env: ${{ matrix.tox_env }}
    strategy:
      matrix:
        tox_env:
        # This information is repeated in tox.ini
        # (see https://github.com/fedora-python/tox-github-action/issues/8)
        # Generate it by: tox -l | sed "s/^/- /"
        - py36-tox3
        - py38-tox3
        - py38-tox4
        - py39-tox3
        - py39-tox4
        - py310-tox3
        - py310-tox4
        - py311-tox3
        - py311-tox4
        - py312-tox3
        - py312-tox4
        - py313-tox3
        - py313-tox4
        - py314-tox4
    # Use GitHub's Linux Docker host
    runs-on: ubuntu-latest
